### ISSUE TITLE
Maps, location and graveyards

### ISSUE THREAD

**Issue by argumumble** [dufernst/FirestormWoD#11]
The server doesn't seem to know where I am really. And it doesn't matter where I am, it tells me that I am in different locations everywhere.

And when you die, you appear at random graveyards when you press "Return to graveyard"

![wowscrnshot_101717_192624](https://user-images.githubusercontent.com/32650129/31680397-7e7ee20a-b374-11e7-8b14-29d247277d96.jpg)
![wowscrnshot_101717_192825](https://user-images.githubusercontent.com/32650129/31680410-82ad18ce-b374-11e7-8a0b-470bd6c3c8f2.jpg)
![wowscrnshot_101717_194246](https://user-images.githubusercontent.com/32650129/31680415-85553e62-b374-11e7-9cc6-83dcf1e57386.jpg)

**Comment by dufernst** [comment]
Did you extract the vmaps/mmaps/maps/dbc yourself? Because you seem to have the wrong data files.

**Comment by argumumble** [comment]
I did extract them from WoWCircle and that gave me some errors, but they work fine ingame atleast more than that.

I'll try to extract the WodEmpire one

**Comment by dufernst** [comment]
Extracted from WoWCircle should be fine, could you try again?
I have no such issues.

**Comment by argumumble** [comment]
Sure thing, just gotta download the client again

**Comment by argumumble** [comment]
This is the errors I got, but it doesn't stop there... This is from the WoDEmpire one

"Detected client build 20726 for locale ruRU

Extracting dbc/db2 files...
Unable to open file DBFilesClient\MovieOverlays in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestObjectiveCliTask in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file DBFilesClient\ConsoleScripts in the archive for locale ruRU: FILE_NOT_FOUND
Extracted 518 files

Locale ptBR not installed.
Locale itIT not installed.
Locale ptPT not installed.
Using locale: ruRU
Extracting maps..."

**Comment by argumumble** [comment]
Forgot to mention, it doesn’t seem to find any locale more than ruRU. And more errors appear when doing this step and the other maps, vmaps and mmaps steps

**Comment by portunus** [comment]
Perhaps try to download dbc files from 6.2.3 or 6.2.4 repack, there a couple of them available on the internet.

**Comment by dufernst** [comment]
I downloaded the English DBC from a repack because WoWCircle is a russian WoW client. Everything else I got by extracting the WoWCircle client.

**Comment by argumumble** [comment]
Alright, nice! I’ll try that!

Going to try to post all the errors I get later when it’s done, thanks!

**Comment by argumumble** [comment]
Here is the log when extracting from WoDEmpire ( I've gotten the exact same errors from WoWCircle)
[vmaps-extractor.txt](https://github.com/dufernst/FirestormWoD/files/1395621/vmaps-extractor.txt)

**Comment by dufernst** [comment]
Are you certain you have the client completed downloaded before extracting?
Either way there is little I can do, it works for me :|

**Comment by argumumble** [comment]
Oh well, thank you a lot anyway dufernst!

Could you maybe upload your maps and so on for me to use?

**Comment by dufernst** [comment]
I prefer not to, I will look into the issue next week (the extractors worked for me so should also work for others).

**Comment by argumumble** [comment]
I understand, thank you for looking into this!

**Comment by argumumble** [comment]
WoD-Empire client isn't complete from where you download it. It seems to be missing ~1GB of files for the map files to be complete.

And before doing any other steps more than extracting the maps, I tried them out and now it's working!
