### ISSUE TITLE
unable to extract dbc and maps

### ISSUE THREAD

**Issue by Dragnell87** [dufernst/FirestormWoD#13]
![sin titulo](https://user-images.githubusercontent.com/8634449/32147229-4856207c-bcba-11e7-8e97-b3cca7ea07d7.png)

I have  a full version of Firestorm client 623.20779 but when i tray to use mapextrator i have the error shows above, could this be because i do not have the .buildinfo file ? If thios is the case how can i generate that file. Thanks in advance.

**Comment by portunus** [comment]
Did you looked at similar problems @ trinitycore, there are many existing issues reported with various possible solutions?

The extractor is working, so if there are problems it should be at the configuration at your end. Perhaps you can try to extract the files from wodempire/wowcircle clients if firestorm isn't working for you.

**Comment by argumumble** [comment]
@dragnell87 Try WoD-Empire, that ones works. I had that problem with the Firestorm one too.

**Comment by Cubansephiroth** [comment]
Same problem as @Dragnell87 with FS client. @argumumble can you or anyone share the files?

**Comment by argumumble** [comment]
@Cubansephiroth Use WoD-Empire client to extract maps and so on

**Comment by Cubansephiroth** [comment]
http://wodempire.com/en/  502 Bad Gateway nginx  -  no luck for me :(

**Comment by dufernst** [comment]
I had no issues with the wowcircle client which is still available:
http://forum.wowcircle.com/en/showthread.php?t=4088

**Comment by Cubansephiroth** [comment]
@dufernst thanks for your answer. No luck with wowcircle startup files. Binaries from x32 and x64 looks for versions and cdns in ashran server. Cant start downloading cause my exe cant find those files. Its not a connection issue. The domains ashran.com seems down from here :*(

**Comment by dufernst** [comment]
They have a torrent with the full client (the first link in the post), I used that client.
In another issue in this repo I link to an exe that does work.

**Comment by Cubansephiroth** [comment]
Torrent is hell for me :( ill try that .exe and comment if success. Thanks again.

**Comment by cooler-SAI** [comment]
why not post all Data in mega ? for easy download

**Comment by Cubansephiroth** [comment]
Would someone be so kind to upload them please? I am very interested in testing the source because I have been able to compile it without problem in Linux. I have two friends developer who can share without problems the fixes we make in case we decide to use the project in our network. But the issue of getting the maps is getting very difficult for us. PLEASE HELP!!!

**Comment by Crandalius** [comment]
You know i wouldn't say it's impossible to fix but the availability of
someone to help isn't as great. I can guarantee you that dufer will be more
than happy to help but don't try to rush perfection. Respect that he
released his fixes to the public cause there is very little people that
would do what he did for us. Give it some time we will get to an conclusion

**Comment by Cubansephiroth** [comment]
I dont try to rush Dufer or anyone else, just called for help. I know his work here is great and i are more than grateful for his fixes especially at fixing linux compile.

**Comment by dufernst** [comment]
Got someone to upload the data:
http://www.mediafire.com/file/x191aw91im1391e/ServerData.7z

**Comment by Cubansephiroth** [comment]
Thankssssssssss @dufernst  You made my day  and dont worry if URL expired i will reupload if needed.
And no more Dufer dont worry xD

**Comment by cooler-SAI** [comment]
THANKS!!!!!! xD
