### ISSUE TITLE
Can't log in - Error 104

### ISSUE THREAD

**Issue by cooler-SAI** [dufernst/FirestormWoD#14]
I have a patched client 6.2.3 20779 (Firestorm) and can't log in
I created account in console:
.account create ander@ander.ru ander
in realmlist.wtf set realmlist 127.0.0.1
in realmlist build 20726. I set to 20779 - can't solved problem

ruRU client
 Can someone help me here? may be I need wow.exe patched 20726 ? can someone upload it? thanks anyway

**Comment by portunus** [comment]
Try using the client of wowcircle (wodempire is down?), firestorm is causing issues if i'm recalling correctly. Firestorm also have their own launcher in which they launch their stuff.

**Comment by cooler-SAI** [comment]
wodempire down, ok, I'll check it

**Comment by dufernst** [comment]
Most clients cause issues now but this one should work:
http://www.mediafire.com/file/nltflkn5nx7fhci/Wow-64-Patched.exe
As I mentioned in a previous comment it does rely on firestorm for the streaming so I would recommend downloading the full client (using the wowcircle torrent) and replacing their exe with the one I linked.

**Comment by cooler-SAI** [comment]
problem solved! thanks for the help,guys)))) 
I set SET portal "localhost" in WTF conf file - and all good now)))
