### ISSUE TITLE
download Links - Client and Data files inside

### ISSUE THREAD

**Issue by cooler-SAI** [dufernst/FirestormWoD#15]
Here we go! thanks to all  who helped me get this Data)) special to **Duf** )))
 **Get dbc,,maps,vmaps,mmaps :** https://mega.nz/#!GUlUlB6J!mefm3EudO3lLn1FLLfJJxv8DH6a1Zh1iCOmQAl_WC48

**Get full World of Warcraft Warlords of Draenor Client 6.2.3 (20779) patched ruRU & enGB:**

part 1 - https://mega.nz/#!OIkXVb7Y!cFWofTc1CzCxvdrF0K_ypL-IYZurRRnnnJY5ZzVwwDk
part 2 - https://mega.nz/#!zFsgDYga!K4KPWaU4LFtN2EBc9K4bJs33IX3g61nwykGzyQCuwxQ
part 3 - https://mega.nz/#!bA8zEJjC!rFAC8LTzhK9aGwUtUUVsZd7drI4O8aKHTHD3rfm15m0
part 4 - https://mega.nz/#!zIUlSSzb!60rfg4mmYzOv6T1fLpP8sNTxGdUkTmOgg0b2BhtF1N8
part 5 - https://mega.nz/#!WB8h0IYL!dlyU6LK0piS9h9mf7b6dDr1VXVVvc2pbjkFegZTvKYI
part 6 - https://mega.nz/#!uU0SwTKS!PUpkBVrsiKjD6gEYwZn3xl2mTuzWC8mYot7QoxqRYFk
part 7 - https://mega.nz/#!rMsjEbLS!7EVdlOjUN-iUcRYKMNvrPO0xOgM_CEo-u4IQjSQd50E

**Comment by Crandalius** [comment]
Good job cooler. Now this is what a community should do!

**Comment by dufernst** [comment]
@cooler-SAI Added your links to the README, thanks!
