### ISSUE TITLE
Wow.exe offline ON?

### ISSUE THREAD

**Issue by cooler-SAI** [dufernst/FirestormWoD#19]
Hey.I have a best connection with my server but have one question: can I run client offline? I have patched exe, I set localhost in realmlist,but client don't wanna run when my internet off. Server show me in game US time and local time.  So,can someone please help me? thanks anyway:grinning:

**Comment by Cubansephiroth** [comment]
Hi cooler, you need an active internet connection in order to run wow.exe (at load wow.exe looks for version and cdns files). ofc you could also host those files in a local webserver and patch your wow.exe to look for them in your webserver instead of internet.

**Comment by cooler-SAI** [comment]
PROBLEM SOLVED!!
just create BAT file:
```
"Wow-64-Patched.exe" -uid localhost
```sql
