### ISSUE TITLE
Opcode Error

### ISSUE THREAD

**Issue by mayor2012** [dufernst/FirestormWoD#2]
I am having this error wen trying to connect the autserver 
BNet2::Session::OnRead Got unknown packet from '127.0.0.1' opcode 22 channel 0 size 159

I think I do not have the patch , and connectionPacther is broken , I am using a 6.2.4 Client build 21742 can any one give me the .exe for this build 20799

**Comment by portunus** [comment]
Check the commits in [https://github.com/dufernst/FirestormWoD/commit/d3c81ffe4515d8a912113d175b918fe824b1e3f9]

**Comment by dufernst** [comment]
A working .exe can be found here:
http://www.mediafire.com/file/nltflkn5nx7fhci/Wow-64-Patched.exe

Getting some unknown packet warnings is fine, the BNet protocol is only partly handled.

**Comment by mayor2012** [comment]
![error2](https://user-images.githubusercontent.com/6295128/30892291-c2615248-a305-11e7-9415-8a9deacd4232.png)
I having this error , I think my client is fuck up , I am downloading WoDempire client

**Comment by dufernst** [comment]
Well I guess that makes sense because the client needed for this core is 6.2.3 and not 6.2.4.

**Comment by mayor2012** [comment]
thanks for the help i am downloading 6.2.3 from WODEMPIRE

**Comment by mayor2012** [comment]
seems that u torrent is locket for me , can anyone send me a URL to download WOD Client 6.2.3 mega drop wherever

**Comment by dufernst** [comment]
You could use the streaming client from Firestorm and replace the .exe with the one uploaded on mediafire.

**Comment by mayor2012** [comment]
so my friends I am about to give up on this , I downloaded the client from WoDEmpire Utorrent and Replace the  .exe with the one dunfernst gave me , and nothing the client does not open, I am so frustrated , I have been trying  for wakes , this is the error that I having now 
![error](https://user-images.githubusercontent.com/6295128/31311699-e341806e-ab7f-11e7-99b8-ca43be4b57ea.png) please some one send me the correct URL client

**Comment by mayor2012** [comment]
I think I know what the problem is , I need a .exe that does not have to go to internet , like trinity legion I do not have to need internet to play it off line, is some one can fix the conection pacher

**Comment by dufernst** [comment]
I have no/very limited experience with reverse engineering so won't be able to help you with that.
You could run a local "webserver" you could add US-cdn-fstorm.cc to your HOSTS file and have it connect to your local server instead of the server from firestorm.
