### ISSUE TITLE
Logging in issues

### ISSUE THREAD

**Issue by 02918765** [dufernst/FirestormWoD#21]
Hello! I want to test out this source but I can't seem to login!

I have downloaded the client torrent from wowcircle, edited the config.wtf to set portal "127.0.0.1" started up the servers, made an account but when I login immediate DC! my realmlist table should be fine and ports 1119 and 8085 are open I am using the wow-64-patched.exe, is there solution for this?

11/17 20:40:10.170  Login program=WoW platform=Wn64 locale=enUS
11/17 20:40:10.170  Component WoW.Wn64.20779
11/17 20:40:10.170  Component WoW.base.20726
11/17 20:40:10.179  Battle.net is Component Bnet.Wn64.37165
11/17 20:40:10.179  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
11/17 20:40:10.217  Failed to resolve 127.0.0.1.
11/17 20:40:10.217  LOGIN: state: LOGIN_STATE_FAILED result: DISCONNECTED 
11/17 20:40:10.217  Login program=WoW platform=Wn64 locale=enUS
11/17 20:40:10.217  Component WoW.Wn64.20779
11/17 20:40:10.217  Component WoW.base.20726
11/17 20:40:10.217  Battle.net is Component Bnet.Wn64.37165
11/17 20:40:10.226  Client Disconnect due to reason:8

**Comment by portunus** [comment]
Did you read closed commits related to this issue? The wowcircle isn't usable to connect with this core, however you can use that client to extract the dbc/map files.

Try using the client as linked in the readme file (https://github.com/dufernst/FirestormWoD/blob/master/README.md)

**Comment by 02918765** [comment]
I thought the full client was available since it said torrent file

**Comment by dufernst** [comment]
Using the torrent should be fine as long as you use the Patched Executable that is linked to in the README.
But:
11/17 20:40:10.217 Failed to resolve 127.0.0.1.
suggests that your configuration is not really correct.
If you can share all the relevant details we can take a look.

**Comment by 02918765** [comment]
https://pastebin.com/c7gm9K6J authserver
https://pastebin.com/bAjwN0u1 worldserver
`INSERT INTO `realmlist` (`id`, `name`, `address`, `port`, `icon`, `flag`, `timezone`, `allowedSecurityLevel`, `motd`, `population`, `gamebuild`, `online`, `delay`, `queue`, `lastupdate`) VALUES
	(1, 'TrinityCore Server', '127.0.0.1', 8085, 0, 0, 1, 0, 'Welcome on our server.', 0, 20726, 0, 10, 0, 1495119746);`

**Comment by dufernst** [comment]
Can you try it with localhost in the Config.wtf instead of 127.0.0.1?

**Comment by 02918765** [comment]
and now suddenly it works..? fixed then, maybe it's cause i restarted my computer lolz
