### ISSUE TITLE
Conencting with LAN

### ISSUE THREAD

**Issue by Crandalius** [dufernst/FirestormWoD#4]
Hi all,

I'm not sure if anyone tried to connect from LAN to the server. I'm not sure if it's on the client side but i keep getting unable to resolve to my specific address. I've made the changes on the db realmlist , client SET portal and also checked if 3724 and 8085 is allowed (which is). Could anyone please point me in the right direction with this issue

Thanks!

**Comment by mayor2012** [comment]
what IP have you put in your realmList table 127.0.0.1 ?? also check firewall Farm in auth database , upload a print screen !

**Comment by Crandalius** [comment]
![image](https://user-images.githubusercontent.com/26557039/31043641-ecea0426-a5bf-11e7-9eb6-577bdb5d9c0f.png)

I'm able to connect from my own PC that's been hosting the sever. to the host. But not the other way around

![image](https://user-images.githubusercontent.com/26557039/31043657-29c96260-a5c0-11e7-8483-d6c504e43392.png)

I've specified my LOCAL IP 

![image](https://user-images.githubusercontent.com/26557039/31043665-4a9b2cb2-a5c0-11e7-8663-6a8aa1a9c373.png)

I'm able to connect from the PC that hosted the server previously but as soon i try to connect from a different PC that's hosting i get this immediate log

9/30 09:11:18.497  Login program=WoW platform=Wn64 locale=enUS
9/30 09:11:18.632  Component WoW.Wn64.20779
9/30 09:11:18.666  Component WoW.base.20726
9/30 09:11:18.722  Battle.net is Component Bnet.Wn64.37165
9/30 09:11:18.756  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
9/30 09:11:18.799  Failed to resolve 192.168.0.2.
9/30 09:11:18.835  LOGIN: state: LOGIN_STATE_FAILED result: DISCONNECTED 
9/30 09:11:18.863  Login program=WoW platform=Wn64 locale=enUS
9/30 09:11:18.901  Component WoW.Wn64.20779
9/30 09:11:18.929  Component WoW.base.20726
9/30 09:11:18.974  Battle.net is Component Bnet.Wn64.37165
9/30 09:11:19.029  Client Disconnect due to reason:8

**Comment by dufernst** [comment]
9/30 09:11:18.799 Failed to resolve 192.168.0.2.
You should look for similar problems with a search engine (by searching for "Failed to resolve local network ip address).
You'll get results like this:
https://superuser.com/questions/713580/unable-to-resolve-localhost-127-0-0-1-or-local-ip-address
with some helpful suggestions.

Good luck :)
