### ISSUE TITLE
repack upload

### ISSUE THREAD

**Issue by spyrobandicoot** [dufernst/FirestormWoD#5]
Hi guys I have a big favour to ask for.

Is there somebody out there who could upload, an already compiled folder for me, like a repack ?

Its a little bit much to ask from a stranger but since I have some problems with my visual studio right now I still would be really happy to check it out.

**Comment by mayor2012** [comment]
look I will be glad to do it but mi internet is 20k/s lol , I used VS2015 , CMAKE3 openssl64 , start with that , and if you have any problem I'll help you

**Comment by spyrobandicoot** [comment]
It doesnt even need to be with maps or something just upload the core folder would be cool, do you have skype?

**Comment by mayor2012** [comment]
https://mega.nz/#!6k5HzLZD!szmxlYHH-NvaVvczPLRYSxD6wJAZA_x5KlIPmDkvIGk

**Comment by spyrobandicoot** [comment]
you are the best thank you, now if only someone could upload dbc it should work, right now its crashing at initalising data store, thats because I use wrong dbc, could you do this for me?
only dbc no maps or something I have that already only the dbc. thanks buddy

**Comment by portunus** [comment]
Did you adjust the allowed client numbers in your database (bnet_allowed_build & realmlist table in the auth database)?

I i'm remember correct it should be 20726
