### ISSUE TITLE
Connecting to the server

### ISSUE THREAD

**Issue by argumumble** [dufernst/FirestormWoD#7]
I have compiled the source into 64-bit and downloaded the .exe that dunfernst provided in another issue. But it seems like I cannot connect to the server at all, I am getting "Battle.net Error 2".

So it kinda feels like it's not connecting? I have "SET PORTAL 127.0.0.1" in my config.wtf but that doesn't change a lot...

Any ideas?

**Comment by dufernst** [comment]
What is battle.net error 2?
Can you enable logging on the authentication server to verify that nothing is connecting?

If nothing is happening @ the authentication server than I assume the client hasn't been configured properly.

**Comment by argumumble** [comment]
I'll get back to you when I got more info, since I am looking around trying to figure out what it means

**Comment by dufernst** [comment]
Good luck, let me know if you have some more info!

**Comment by argumumble** [comment]
So I figured out what the BNET error 2 was all about and what it means. There is something around the client not finding the server on the set SET PORTAL and/or port, thinking the server is down.

But now I got another problem... I have the Error 114, any way around that?

**Comment by argumumble** [comment]
I managed to fix this myself, again with some trial and error. Thank you dunfernst for all your help!
