### ISSUE TITLE
Friend cannot connect to server

### ISSUE THREAD

**Issue by argumumble** [dufernst/FirestormWoD#9]
Not sure what this is all about, but it fails to resolve my Hamachi IP somehow. I can login and everything is fine, but his client seems to fail on this part

10/13 12:51:00.975  Login program=WoW platform=Wn64 locale=enUS
10/13 12:51:01.049  Component WoW.Wn64.20779
10/13 12:51:01.077  Component WoW.base.20726
10/13 12:51:01.102  Battle.net is Component Bnet.Wn64.37165
10/13 12:51:01.115  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
10/13 12:51:01.157  Failed to resolve 25.75.182.74.
10/13 12:51:01.165  LOGIN: state: LOGIN_STATE_FAILED result: DISCONNECTED 
10/13 12:51:01.186  Login program=WoW platform=Wn64 locale=enUS
10/13 12:51:01.199  Component WoW.Wn64.20779
10/13 12:51:01.220  Component WoW.base.20726
10/13 12:51:01.250  Battle.net is Component Bnet.Wn64.37165
10/13 12:51:01.290  Client Disconnect due to reason:8

**Comment by portunus** [comment]
Try looking at similar problems @ trinitycore
